# set-up basic server

---

  - user:
      name: cladmin
      uid: 1000
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa      
      comment: "admin user, for support"
      state: present

  - group:
      name: critlib
      gid: 2000

  - user:
      name: critlib
      uid: 2000
      groups: "wheel,evs"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa      
      comment: "critlib user, for running docker containers"
      state: present

  - name: Allow evs critlib to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^critlib'
      line: 'critlib ALL=(ALL) NOPASSWD: ALL'

  - name: set hostname to value from inventory
    hostname:
      name: "{{ inventory_hostname }}"

  - name: install epel
    yum:
      name: epel-release
      state: latest

  - name: install python
    yum:
      name: python
      state: latest

  - name: install docker-python
    yum:
      name: docker-python
      state: latest

  - name: upgrade latest
    yum:
      name: "*"
      state: latest

  - name: create directory /opt/critlib
    file: path=/opt/critlib state=directory owner=critlib group=critlib mode=0755

  - name: create log directory for evs applications
    file: path=/var/log/critlib state=directory owner=critlib group=critlib mode=0755

  - name: create directory /etc/critlib
    file: path=/etc/critlib state=directory owner=critlib group=critlib mode=0750

  - name: install config file
    copy:
      src: config
      dest: /etc/critlib/config
      owner: critlib
      group: critlib
      mode: "u=rw,g=r"

...
