# set-up basic server

---

  - group:
      name: pgadmin
      gid: 2000

  - user:
      name: pgadmin
      uid: 2000
      groups: "wheel,pgadmin"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa      
      comment: "user for running docker containers"
      state: present

  - name: Allow passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^pgadmin'
      line: 'pgadmin ALL=(ALL) NOPASSWD: ALL'

  - name: set hostname to value from inventory
    hostname:
      name: "{{ inventory_hostname }}"

  - name: install epel
    yum:
      name: epel-release
      state: latest

  - name: install python
    yum:
      name: python
      state: latest

  - name: install docker-python
    yum:
      name: docker-python
      state: latest

  - name: upgrade latest
    yum:
      name: "*"
      state: latest

  - name: create directory /opt/pgcluster
    file: path=/opt/pgcluster state=directory owner=pgadmin group=pgadmin mode=0755

  - name: create log directory for evs applications
    file: path=/var/log/pgcluster state=directory owner=pgadmin group=pgadmin mode=0755

  - name: create directory /etc/pgcluster
    file: path=/etc/pgcluster state=directory owner=pgadmin group=pgadmin mode=0750

  - name: install config file
    template:
      src: config.j2
      dest: /etc/pgcluster/config
      owner: pgadmin
      group: pgadmin
      mode: "u=rw,g=r"

...
