version: '3.2'
services:
  pg01:
    image: pg:${pg_version}
    environment:
      INITIAL_NODE_TYPE: master
      NODE_ID: 1
      NODE_NAME: pg01
      MSLIST: "asset,ingest,playout" 
              # for each micro-service two db users are created, for ex. asset_owner and asset_user, etc.
      MSOWNERPWDLIST: "asset_owner,ingest_owner,playout_owner"
      MSUSERPWDLIST: "asset_user,ingest_user,playout_user"
      REPMGRPWD: rep123
      PGMASTER: pg01
      REPMGRD_FAILOVER_MODE: manual
    volumes:
      - /u01/pg10/data:/data
      - /u02/archive:/archive
      - /u02/backup:/backup
      - /etc/localtime:/etc/localtime
    deploy:
      placement:
        constraints:
          - node.id == {{ docker_node_1 }}
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

  pg02:
    image: pg:${pg_version}
    environment:
      INITIAL_NODE_TYPE: slave
      NODE_ID: 2
      NODE_NAME: pg02
      MSLIST: "asset,ingest,playout" 
              # for each micro-service two db users are created, for ex. asset_owner and asset_user, etc.
      MSOWNERPWDLIST: "asset_owner,ingest_owner,playout_owner"
      MSUSERPWDLIST: "asset_user,ingest_user,playout_user"
      REPMGRPWD: rep123
      PGMASTER: pg01
      REPMGRD_FAILOVER_MODE: manual
    volumes:
      - /u01/pg10/data:/data
      - /u02/archive:/archive
      - /u02/backup:/backup
      - /etc/localtime:/etc/localtime
    deploy:
      placement:
        constraints:
          - node.id == {{ docker_node_2 }}
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    depends_on:
      - pg01

  pgpool:
    image: pgpool:${pg_version}
    ports:
      - 9999:9999
    environment:
      PGMASTER_NODE_NAME: pg01
      PG_BACKEND_NODE_LIST: 0:pg01:5432:1:/data:ALLOW_TO_FAILOVER,1:pg02:5432:1:/data:ALLOW_TO_FAILOVER
                # csv list of backend postgres databases, each backend db contains (separated by :)
                # number (start with 0):host name:pgpool port (default 9999):data dir (default /data):flag ALLOW_TO_FAILOVER or DISALLOW_TO_FAILOVER
                # not needed when there is a single postgres DB
      PGP_NODE_NAME: pgpool
      REPMGRPWD: rep123
      FAILOVER_MODE: automatic
      PGPOOL_HEALTH_CHECK_MAX_RETRIES: 6
      PGPOOL_HEALTH_CHECK_RETRY_DELAY: 5
      #DELEGATE_IP: 172.18.0.100
      #TRUSTED_SERVERS: 172.23.1.250
      #PGP_HEARTBEATS: "0:pgpool01:9694,1:pgpool02:9694"
      #PGP_OTHERS: "0:pgpool02:9999"
                # csv list of other pgpool nodes, each node contains (separated by :)
                # number (start with 0):host name:pgpool port (default 9999)
                # not needed when there is a single pgpool node
    depends_on:
      - pg01
      - pg02

  manager:
    image: manager:${manager_version}
    ports:
      - 8080:8080
    environment:
      PG_BACKEND_NODE_LIST: 0:pg01:5432:1:/data:ALLOW_TO_FAILOVER,1:pg02:5432:1:/data:ALLOW_TO_FAILOVER
      REPMGRPWD: rep123
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
