---

  # this file can be included when you want to upload a docker
  # image from the staging dir to the server.
  # it will first check if the image is already present with the same id, in which case it does nothing
  #
  # parameter: image. It is a dict object containing name, id, tag,file. It is passed as parameter in the include

  #- name: check what is in item
  #  debug: var=image

  - name: check image id on the server
    shell: docker images -q {{image.name}}:{{image.tag}}
    register: docker_image

  #- debug: var=docker_image

  - name: check on the host
    shell: ls /tmp | grep -q {{ image.file }}
    register: file_present
    failed_when: false
    ignore_errors: yes
    changed_when: false
    when: docker_url is not defined

  - name: see file_present
    debug: var=file_present
    when: docker_url is not defined

  - name: copy file
    copy:
      src: "{{stage_dir}}/{{ image.file }}"
      dest: /tmp
    when:
      - docker_url is not defined
      - file_present.rc != 0
      - docker_image.stdout != "{{ image.id }}"

  - name: load docker image
    shell: docker load --input=/tmp/{{ image.file }}
    when: docker_url is not defined and docker_image.stdout != "{{ image.id }}"

  - name: check image id on the server
    shell: docker images -q {{image.name}}:{{image.tag}}
    register: docker_image
    when: docker_url is not defined

  - assert:
      that:
        - image.id in docker_image.stdout
      msg : "loaded image id must match"
    when: docker_url is not defined

  - name: load docker image
    docker_image:
      name: "{{ docker_url}}{{ image.name }}"
      tag: "{{ image.tag }}"
    when: docker_url is defined

  - name: remove image from /tmp
    file: 
      path: "/tmp/{{ image.file }}"
      state: absent
    when: docker_url is not defined

...

