version: '3.2'
services:
  pg01:
    image: pg:${pg_version}
    environment:
      INITIAL_NODE_TYPE: master
      NODE_ID: 1
      NODE_NAME: pg01
      MSLIST: "myservice" 
              # for each micro-service two db users are created, for ex. asset_owner and asset_user, etc.
      MSOWNERPWDLIST: "myservice_owner"
      MSUSERPWDLIST: "myservice_user"
      REPMGRPWD: rep123
      REPMGRD_FAILOVER_MODE: manual
      REPMGRD_RECONNECT_ATTEMPS: 5
      REPMGRD_INTERVAL: 1
      PGMASTER: pg01
    ports:
      - 15432:5432 # postgres port
    volumes:
      - pg01db:/u01/pg10/data
      - pg01arc:/u02/archive
    networks:
      - pgcluster_network
  pg02:
    image: pg:${pg_version}
    environment:
      INITIAL_NODE_TYPE: slave
      NODE_ID: 2
      NODE_NAME: pg02
      MSLIST: "myservice" 
              # for each micro-service two db users are created, for ex. asset_owner and asset_user, etc.
      MSOWNERPWDLIST: "myservice_owner"
      MSUSERPWDLIST: "myservice_user"
      REPMGRPWD: rep123
      REPMGRD_FAILOVER_MODE: manual
      REPMGRD_RECONNECT_ATTEMPS: 5
      REPMGRD_INTERVAL: 1
      PGMASTER: pg01
    ports:
      - 25432:5432 # postgres port
    volumes:
      - pg02db:/u01/pg10/data
      - pg02arc:/u02/archive
    networks:
      - pgcluster_network
    depends_on:
      - pg01

  pgpool:
    image: pgpool:${pg_version}
    ports:
      - 9999:9999
    environment:
      PGMASTER_NODE_NAME: pg01
      PG_BACKEND_NODE_LIST: 0:pg01:5432:1:/u01/pg10/data:ALLOW_TO_FAILOVER,1:pg02:5432:1:/u01/pg10/data:ALLOW_TO_FAILOVER
      #PG_BACKEND_NODE_LIST: 0:pg01:5432:1:/u01/pg10/data:ALLOW_TO_FAILOVER,1:pg02:5432:1:/u01/pg10/data:ALLOW_TO_FAILOVER
                # csv list of backend postgres databases, each backend db contains (separated by :)
                # number (start with 0):host name:pgpool port (default 9999):data dir (default /u01/pg10/data):flag ALLOW_TO_FAILOVER or DISALLOW_TO_FAILOVER
                # not needed when there is a single postgres DB
      PGP_NODE_NAME: pgpool
      REPMGRPWD: rep123
      FAILOVER_MODE: automatic
      PGPOOL_HEALTH_CHECK_PERIOD: 5
      PGPOOL_FAIL_OVER_ON_BACKEND_ERROR: "no"
      PGPOOL_HEALTH_CHECK_MAX_RETRIES: 3
      PGPOOL_HEALTH_CHECK_RETRY_DELAY: 1
      PGPOOL_LOAD_BALANCE_MODE: "no"
      #DELEGATE_IP: 172.18.0.100
      #TRUSTED_SERVERS: 172.23.1.250
      #PGP_HEARTBEATS: "0:pgpool01:9694,1:pgpool02:9694"
      #PGP_OTHERS: "0:pgpool02:9999"
                # csv list of other pgpool nodes, each node contains (separated by :)
                # number (start with 0):host name:pgpool port (default 9999)
                # not needed when there is a single pgpool node
    #command: tail -f /etc/hosts
    networks:
      - pgcluster_network
    depends_on:
      - pg01
      - pg02

volumes:
  pg01db:
  pg02db:
  pg01arc:
  pg02arc:

networks:
  pgcluster_network:
    external: true
