---

- hosts: all

  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    # do_swarm: set to false to avoid reconfig of the swar, this part is not idempotent and does not work well
    do_swarm: true
    docker_url: 192.168.1.57:5000/
    insecure_registries: ["192.168.1.57:5000"]
    images: 
      manager:
        tag: "0.7.7"
        id: "1df033793360"
        name: "manager"
      pgpool:
        tag: "0.7.7"
        id: "1df033793360"
        name: "pgpool"
      postgres:
        tag: "0.7.7"
        id: "bf1d8c535fff"
        name: "pg"
    pgpool_ip_failover: 172.22.1.50
    pgpool_ip_failover_netmask: 24
    pgpool_ip_failover_interface: eth1
    pgpool_trusted_servers: 192.168.1.57
    swarm_interface: "eth1"
    master_swarm_interface: "eth1"

  pre_tasks:

  # let us use a group called cluster if it is not explicitly defined in the inventory file
  - add_host:
      name: "{{ item }}"
      groups: cluster
    with_items: "{{ groups.all }}"
    when: groups.cluster is undefined
    changed_when: false
    tags: ['init']

  roles:
    - { role: base, tags: ['init'] }
    - { role: docker-ce, tags: ['init'] }
    - { role: postgres, tags: ['init'] }
    - role: docker_swarm
      when: do_swarm
    - role: cluster
    - role: cluster-watchdog
    - role: haproxy

  handlers:
    - name: restart firewalld
      systemd:
        name: firewalld
        state: restarted

    - name: restart docker
      systemd:
        name: docker
        state: restarted
...
