---

- hosts: all

  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    do_swarm: false
    docker_url: 192.168.1.39:5000/
    insecure_registries: ["192.168.1.39:5000"]
    images: 
      manager:
        tag: "0.7.6"
        id: "1df033793360"
        name: "manager"
      pgpool:
        tag: "0.7.6"
        id: "1df033793360"
        name: "pgpool"
      postgres:
        tag: "0.7.6"
        id: "bf1d8c535fff"
        name: "pg"
    pgpool_ip_failover: 192.168.122.250
    pgpool_ip_failover_netmask: 24
    pgpool_ip_failover_interface: eth0
    pgpool_trusted_servers: 192.168.1.39

  pre_tasks:

  # let us use a group called cluster if it is not explicitly defined in the inventory file
  - add_host:
      name: "{{ item }}"
      groups: cluster
    with_items: "{{ groups.all }}"
    when: groups.cluster is undefined
    changed_when: false
    tags: ['init']

  roles:
    - { role: base, tags: ['init'] }
    - { role: docker-ce, tags: ['init'] }
    - { role: postgres, tags: ['init'] }
    - role: docker_swarm
      when: do_swarm
    - role: cluster
    - role: cluster-watchdog
    - role: haproxy

  handlers:
    - name: restart firewalld
      systemd:
        name: firewalld
        state: restarted

    - name: restart docker
      systemd:
        name: docker
        state: restarted
...
