---


- hosts: all

  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - { role: base, tags: ['init'] }
    - { role: docker-ce, tags: ['init'] }
    - { role: postgres, tags: ['init'] }

...
